### ISSUE TITLE
look for suitable IR model for new crowd counting video 

### ISSUE THREAD

**Issue by yimm0815** [OpenVisualCloud/Smart-City-Sample#324]
found the video https://www.pexels.com/video/aerial-footage-of-a-game-of-soccer-2657261/  suit for smart stadium crowd counting use case even better. However, current CSRNet model doesn't suit for this video yet. 1/8 down-sampling makes the audience get trimmed down thus unable to recognize. assign @dahanhan to investigate substitute IR model.

**Comment by dahanhan** [comment]
This video is super high crowded with over 1,000 persons on the grandstand. The current CSRNet model is trained on ShanghaiTech dataset which has average 501 persons in each image. Some frequently used dataset can be found from https://github.com/gjy3035/Awesome-Crowd-Counting#Datasets. Some dataset with more persons in each image, UCF_CC_50 or UCF-QNRF for instance, could be more fit for fine tune and provide more accurate prediction for this video.  
Downsampling is not really done on the input image before inference process. The feature map is generated by multiple convolution layter to extract image features finally generated a 1/8 size density map. The root cause is the mismatch between video and model weights.
